### ISSUE TITLE
Public dataset?

### ISSUE THREAD

**Issue by deeppomf** [hepesu/LineDistiller#1]
The README mentions the dataset will be made public soon. Do you know when you will make it available?

**Comment by hatsuame** [comment]
Due to the rejection of nico dataset, the public dataset might be delayed. I am sorry.

**Comment by hepesu** [comment]
I am working with nico-illust dataset now. It might be done before June. Unfortunately, the nico-illust contains too many useless data, and only few of them can be used as accepted data pairs. I think the dataset may contain 2000 line-color pairs. I will keep you posted for any updated infomation.

**Comment by hepesu** [comment]
Due to limitation of datasets, I provide toolset to create dataset instead of a pre-built dataset. This overcomes some copyright limitations.
